### ISSUE TITLE
circleci/codecov does not exist and codecov/codecov issues with alpine

### ISSUE THREAD

**Issue by tsloughter** [CircleCI-Public/circleci-orbs#100]
The codecov orb in this repo doesn't appear to be published at all. And the codecov/codecov orb will not work on alpine, even if bash is installed because the command still runs with shell sh and so even though it runs `bash` the use of `<( )` causes it to fail.

I can't find a repo for codecov/codecov so I can not send a patch, maybe simply adding `shell: bash` to the command would do it.

This circleci/codecov orb works fine, so it would be great if it were published.

**Comment by iynere** [comment]
huh, it's definitely published https://circleci.com/orbs/registry/orb/circleci/codecov @tsloughter 

is this still an issue for you ?

**Comment by tsloughter** [comment]
Hm, maybe it is because I copied from the example without thinking. I just noticed the example has `codecov: circleci/codecov@1.0.0` but the latest version is `0.0.3`. I bet when I tried it before I had simply copied from that example :(

Sorry about the confusion, it works.

**Comment by iynere** [comment]
we'll get this orb to v1.0.0 soon @tsloughter 

we put 1.0.0 as a standard in all our examples b/c it's a simple, easy to understand number, but i apologize for the confusion here. thank you !
