### ISSUE TITLE
Gradle Orb: with_cache should allow custom key

### ISSUE THREAD

**Issue by BjoernPetersen** [CircleCI-Public/circleci-orbs#132]
It's common, especially for Gradle Kotlin DSL users, to store dependency versions outside the `build.gradle.kts` file. There should be a way to specify files containing those versions for the `with_cache` command.

**Comment by evant** [comment]
Have another reason for this: I'm running the same build under 2 executors. Since the cache keys are the same it's incorrectly trying to restore the cache from one to the other which fails.

**Comment by iynere** [comment]
@BjoernPetersen @evant feel free to open a PR—should be fairly easy to add this—otherwise we will try to get to it soon, thank you !

**Comment by KyleTryon** [comment]
Hello,

We have completed our transition of moving each orb within this Mono repository into a separate repository. 🎉 

We have addressed this issue here: https://github.com/CircleCI-Public/gradle-orb/pull/2
