### ISSUE TITLE
Heroku deploy command does not support maintenance-mode param

### ISSUE THREAD

**Issue by merwok** [CircleCI-Public/circleci-orbs#139]
### Orb version
circleci/heroku 0.0.6

### What happened

I’d like to replace custom steps with orb usage.

The deploy-via-git **job** supports a `maintenance-mode` param, which runs `heroku maintenance:on` before pushing the code.

I’m not using this job because I need to run a command provided by the slack orb, and I think params in the workflow section make things a little messy, so I kept my original jobs and replaced steps with orb commands.

The deploy-via-git **command** doesn’t have a `maintenance-mode` param, so I need to add `heroku/install` and keep the manual call to `heroku maintenance:on`.

### Expected behavior

Jobs and commands in the heroku orb should have the same configurability.

**Comment by felicianotech** [comment]
I could see this go either way with maintenance mode being a seperate command as well.

Considering the job and command here have the *exact* same name, I am leaning on the side it the command supporting the same maintenance mode parameter.

**Comment by iynere** [comment]
feel free to submit a PR—seems like it will be an easy fix @merwok

**Comment by iynere** [comment]
ahh, i see @felicianotech already did :)

**Comment by iynere** [comment]
github is having a webhook problem, so i will attempt to publish the updated version manually @merwok

**Comment by iynere** [comment]
please give this a shot with `circleci/heroku@0.0.7` @merwok if that doesn't work, feel free to file a new issue describing any bugs you encounter—thanks !!

**Comment by merwok** [comment]
Thanks, I will try version 0.0.8.

I have to say that the registry page is rather confusing though (command vs job vs step?) and examples unclear.

**Comment by iynere** [comment]
this may help you @merwok 

https://circleci.com/docs/2.0/reusing-config
https://circleci.com/docs/2.0/configuration-reference/

**Comment by merwok** [comment]
I know that quite well, it’s really the 2.1 orb usage that’s not 100% clear :)

**Comment by merwok** [comment]
I replaced my custom steps by heroku commands!
It’s not just one line because you still need `executor: heroku/default` and steps `checkout` and `heroku/install`, but it’s pretty great.  No more shell commands and YAML reuse, only orbs commands!

(could not use the command directly in the job section of a workflow because I also need slack/status which needs to be a step, and I was not ready to move from one workflow with branch filters on jobs to multiple workflows)
