### ISSUE TITLE
/bin/bash: line 2: --delete: command not found

### ISSUE THREAD

**Issue by jcampbell05** [CircleCI-Public/circleci-orbs#147]
### Orb version

1.0.6
### What happened

https://circleci.com/gh/AIWIP/printt-cloud-print/596

### Expected behavior

It should do whatever it was trying to do without crashing

**Comment by felicianotech** [comment]
@iynere I think this is an issue with quotes, thoughts?

**Comment by iynere** [comment]
@jcampbell05 sorry, what orb were you using ?

**Comment by iynere** [comment]
@jcampbell05 have you tried using the latest version of the orb ? (1.0.7)

**Comment by iynere** [comment]
no i think we're missing a `\` @felicianotech

**Comment by iynere** [comment]
@jcampbell05 please try now with version `1.0.8` of the orb
