### ISSUE TITLE
Don't use bashisms

### ISSUE THREAD

**Issue by DWSR** [CircleCI-Public/circleci-orbs#163]
### Orb version

At least `aws-s3@1.0.0`, using `python:3.7.3-alpine3.9`. Probably others as well.

### What happened
```
#!/bin/sh -eo pipefail
if [[ $(command -v pip) == "" ]]; then
  echo "PIP is required to install AWS CLI and is not available."
  exit 1
else
  if [[ $(command -v sudo) == "" ]]; then
    echo "SUDO is required to install AWS CLI and is not available."
    exit 1
  else
    if [[ $(command -v aws) == "" ]]; then
      sudo pip install awscli
    else
      echo "AWS CLI is already installed."
    fi
  fi
fi
sh: : unknown operand
sh: : unknown operand
AWS CLI is already installed.
```

```
#!/bin/sh -eo pipefail
aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default
aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
/bin/sh: aws: not found
Exited with code 127
```

### Expected behavior

The scripts should work properly.

This is being caused by using bashism (both `-o pipefail and [[ .. ]]`), but specifying `/bin/sh` in the shebang. Any `/bin/sh` compatible shell (such as Busybox/ash in Alpine) fails to parse the script correctly.

Edit: For anyone stumbling upon this issue later, the script being referred to above is from this repo: https://github.com/circleci-public/aws-cli-orb

**Comment by iynere** [comment]
@DWSR we tend to assume bash in most of our orbs—we try to be as agnostic as possible, but we have to make _some_ baseline assumptions, & bash is a better one to make than some others—it's as easy as `apk add bash` to fix

but if you're saying we hardcode `bin/sh` in the script, but then use bashisms in the code, then that's something we should fix

& either way, we should document prerequisites better, imo

**Comment by DWSR** [comment]
> @DWSR we tend to assume bash in most of our orbs—we try to be as agnostic as possible, but we have to make _some_ baseline assumptions

A good baseline assumption is an `sh`-compatible shell, since that's required in every Linux distro under the sun and even Bash has `sh`-compatible mode when invoked as `/bin/sh`. The script referenced here is not particularly complex that Bash is providing any benefit, and I'm willing to bet real dollars that most of the other ones in the official orbs aren't either, especially if they're doing similar jobs.

> bash is a better one to make than some others—it's as easy as `apk add bash` to fix

Whether or not it's easy to fix is besides the point, I think, since it's just as easy for me to satisfy the requirements for orbs in my image as it is for you to update the images to be universally compatible and never trip people up with this problem again.

> but if you're saying we hardcode `bin/sh` in the script, but then use bashisms in the code, then that's something we should fix & either way, we should document prerequisites better, imo

Agreed.

Oh, and `#!/bin/sh -eo pipefail` isn't even a proper shebang line. `-eo pipefail` is passed as a single parameter, not two: https://en.wikipedia.org/wiki/Shebang_(Unix)#Portability

**Comment by iynere** [comment]
@DWSR a lot of our other orbs actually do use a lot of really powerful bashisms that wouldn't be easy or possible with `sh` without other tools that folks might have to install.... but this certainly isn't one of those examples

that said, it's more complexity for us to manage different shell expectations across our orbs fleet, than it is for us to just assume bash universally, & document that assumption so folks know about it

**Comment by iynere** [comment]
going to close this, though, as `#!/bin/sh -eo pipefail` is not actually part of our orb source at all—that's just the default output of the circleci step (we output the shell used to run the command—we also default to `bash` & only fall back to `sh` if `bash` isn't available)

**Comment by iynere** [comment]
so to summarize, unless you see bashisms somewhere here:

https://github.com/CircleCI-Public/circleci-orbs/blob/master/src/aws-s3/orb.yml

then this is not an issue with the orb—& there actually isn't a prerequisites issue, either, at least not for the `s3` orb

**Comment by unixorn** [comment]
If you're going to use bashisms, then use `/bin/bash` in your shebang instead of assuming `/bin/sh` is really `bash` - it isn't in a lot of places.

**Comment by iynere** [comment]
there aren't bashisms in this orb, unless someone can point one out here: https://github.com/CircleCI-Public/circleci-orbs/blob/master/src/aws-s3/orb.yml @unixorn

**Comment by iynere** [comment]
orbs don't set or control the shebang—that's simply the default behavior of our config processor:

https://circleci.com/docs/2.0/configuration-reference/#default-shell-options

if you would like to continue having this addressed as a bug, i suggest you file a support ticket so it can be escalated to the engineers who work on that part of the system:

https://support.circleci.com/hc/en-us/requests/new

thanks !

**Comment by DWSR** [comment]
> there aren't bashisms in this orb, unless someone can point one out here: https://github.com/CircleCI-Public/circleci-orbs/blob/master/src/aws-s3/orb.yml @unixorn

The bashisms are in a dependant orb, https://github.com/CircleCI-Public/aws-cli-orb/blob/master/src/%40orb.yml

**Comment by iynere** [comment]
ahhhhh good point @DWSR hmmmmmm for now i'll document it in the s3 orb's description, but going forward i'm starting a conversation internally around how we should handle dependencies on `bash` across our orb fleet. thank you !
