### ISSUE TITLE
Don't Check for pip or sudo if aws is already present

### ISSUE THREAD

**Issue by DWSR** [CircleCI-Public/circleci-orbs#164]
### Orb version

`aws-s3@1.0.0`

### What happened

If the `awscli` is already present (i.e. `aws` is in PATH), the `Install AWS CLI` step will still check for the presence of `pip` and `sudo`

### Expected behavior

The step should see that the command is present and exit successfully.

**Comment by iynere** [comment]
@DWSR can you file this issue against the aws-cli orb ? i think the code you're referring to lives there, & not in the s3 orb:

https://github.com/circleci-public/aws-cli-orb

**Comment by DWSR** [comment]
Filed https://github.com/CircleCI-Public/aws-cli-orb/issues/13
