### ISSUE TITLE
Don't Check for sudo if already root

### ISSUE THREAD

**Issue by DWSR** [CircleCI-Public/circleci-orbs#165]
### Orb version

`aws-s3@1.0.0`

### What happened

The `Install AWS CLI` script checks for the presence of `sudo` in PATH, even if already running as root.

### Expected behavior

The script should skip checking for sudo if already running as `root`.

**Comment by iynere** [comment]
@DWSR same for this one—can you file against https://github.com/circleci-public/aws-cli-orb ? thanks !

**Comment by DWSR** [comment]
Filed https://github.com/CircleCI-Public/aws-cli-orb/issues/12
