### ISSUE TITLE
AWS CodeDeploy Orb: Stopping a deployment in CodeDeploy leads to a successful result in CircleCI

### ISSUE THREAD

**Issue by jlenos** [CircleCI-Public/circleci-orbs#167]
### Orb version

0.0.9

### What happened

Manually stopped a deployment using CodeDeploy in AWS and it led to a successful deployment result in CircleCI for the deploy-bundle command.

### Expected behavior

Manually stopping a deployment using CodeDeploy should lead to a failed deployment result in CircleCI for the deploy-bundle command.

**Comment by iynere** [comment]
@jlenos can you drop a link to the job where this happened, so we can investigate ? thank you !

**Comment by jlenos** [comment]
https://circleci.com/bb/inflightcorp/aura_circleci/559

I'm seeing this in the result:

        "status": "Stopped", 
        "deploymentOverview": {
            "Skipped": 0, 
            "Succeeded": 0, 
            "Failed": 1, 
            "Ready": 0, 
            "InProgress": 0, 
            "Pending": 0
        },

**Comment by lokst** [comment]
Closing this issue as it looks like it should be fixed in `circleci/aws-code-deploy@0.0.12`, but feel free to reopen it if not.
