### ISSUE TITLE
maven orb: should support mvnw

### ISSUE THREAD

**Issue by gionn** [CircleCI-Public/circleci-orbs#174]
### Orb version

0.0.8

### What happened

`mvn` command is hard-coded in `with_cache` command.

### Expected behavior

I should be able to override the default maven command (I am using maven wrapper - `./mvnw` instead of `mvn`)

**Comment by iynere** [comment]
sounds like an easy fix—we can create a parameter, like, `maven-command`—wanna take a shot at a PR ? @gionn 

thank you !
