### ISSUE TITLE
upgrade aws-s3 base image to python 3?

### ISSUE THREAD

**Issue by zhuangya** [CircleCI-Public/circleci-orbs#182]
### Orb version

aws-s3@volatile

### What happened

nothing, but python 2 is about to retired.

### Expected behavior

upgrade aws-s3 base image to python 3?
https://github.com/CircleCI-Public/circleci-orbs/blob/5f4aba3265497162aca0461bcce7053d0a9f7e1a/src/aws-s3/orb.yml#L17

**Comment by gagandeepp** [comment]
I am on it

**Comment by eddiewebb** [comment]
Is a parameter in new orb - https://github.com/CircleCI-Public/aws-cli-orb/blob/master/src/%40orb.yml#L18
