### ISSUE TITLE
aws-code-deploy fails to check the existence of deployment group with extra arguments passed

### ISSUE THREAD

**Issue by pcwiek** [CircleCI-Public/circleci-orbs#185]
### Orb version
0.0.9
### What happened

Any arguments passed to `aws-code-deploy/create-deployment-group` which are intended for group creation are also passed to AWS CLI when calling `aws deploy get-deployment-group`, which makes the check for group existence fail each and every time because those options are not recognized by `get-deployment-group`. Then the step tries to create the group again and fails every time because the deployment group with specified name already exists.

`CIRCLE_WORKFLOW_ID=cf22d16d-2421-4a55-9ae0-2327f7b11fd6`

Example below is adapted from one of the steps from workflow above

**`ensure-deployment-created`**
```
set +e
aws deploy get-deployment-group \
  --application-name my-app \
  --deployment-group-name test --ec2-tag-filters Key=environment,Value=test,Type=KEY_AND_VALUE --auto-rollback-configuration enabled=true,events=DEPLOYMENT_FAILURE
if [ $? -ne 0 ]; then
  set -e
  echo "No deployment group named test found. Trying to create a new one"
  aws deploy create-deployment-group \
    --application-name my-app \
    --deployment-group-name test \
    --deployment-config-name CodeDeployDefault.OneAtATime \
    --service-role-arn $CODEDEPLOY_ROLE_ARN --ec2-tag-filters Key=environment,Value=test,Type=KEY_AND_VALUE --auto-rollback-configuration enabled=true,events=DEPLOYMENT_FAILURE
else
  set -e
  echo "Deployment group named test already exists. Skipping creation."
fi
```
Output:

```
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: --ec2-tag-filters, Key=environment,Value=test,Type=KEY_AND_VALUE, --auto-rollback-configuration, enabled=true,events=DEPLOYMENT_FAILURE, 
No deployment group named test found. Trying to create a new one

An error occurred (DeploymentGroupAlreadyExistsException) when calling the CreateDeploymentGroup operation: An Deployment Group with the name test already exists for this application.
Exited with code 255
```

### Expected behavior

Either the arguments should be split in two (arguments to `get-deployment-group` and `create-deployment-group` separately), or they should be only used for `create-deployment-group` and omitted for `get-deployment-group` call.

**Comment by KyleTryon** [comment]
Hello, 
Thank you for your contribution! As we are migrating this mono repository into separate repos we can cloned this issue/PR to the new repo location here: https://github.com/CircleCI-Public/aws-code-deploy-orb/pull/2

Thank you.
