### ISSUE TITLE
Break circleci/aws-s3 orb into its own repository

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/circleci-orbs#186]
This repository is a monorepo of orbs and we no longer want that. The `circleci/aws-s3` orb should be broken out into its own repository.

A great way to do this is to use the [Orb Starter Kit](https://github.com/CircleCI-Public/orb-starter-kit) (OSK). The OSK will help you create the scaffolding needed for an orb. Then, the orb source from within this repo can be copied over into your scaffold, eventually creating a brand new orb source repository.

You can then link here to your new repository containing the orb.

**Comment by caseydbrown** [comment]
Hey I would like to try and complete this. Which namespace should the orb sit in? I am assuming CircleCI-Public but not entirely sure.

**Comment by gagandeepp** [comment]
can you assign this to me?

**Comment by michizhou** [comment]
@felicianotech I have included a link to my version of the new repository with the orb source:
https://github.com/michizhou/aws-s3-orb/tree/master. I have also created a PR with the source for the aws-s3 inside this repo modified accordingly. Please let me know if further changes are needed.

**Comment by KyleTryon** [comment]
Thank you @michizhou! We may fork your project soon.
