### ISSUE TITLE
Break circleci/codecov-clojure orb into its own repository

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/circleci-orbs#187]
This repository is a monorepo of orbs and we no longer want that. The `circleci/codecov-clojure` orb should be broken out into its own repository.

A great way to do this is to use the [Orb Starter Kit](https://github.com/CircleCI-Public/orb-starter-kit) (OSK). The OSK will help you create the scaffolding needed for an orb. Then, the orb source from within this repo can be copied over into your scaffold, eventually creating a brand new orb source repository.

You can then link here to your new repository containing the orb.

**Comment by sccalabr** [comment]
https://github.com/sccalabr/codecov-clojure

**Comment by gagandeepp** [comment]
@sccalabr  first fork the original repo then push your changes to the forked repo.
There you have option to create a PR

**Comment by michizhou** [comment]
@felicianotech I have included a link to my version of the new repository with the orb source:
https://github.com/michizhou/codecov-clojure-orb. I also created a PR with the source for the codecov-clojure orb of this repo modified accordingly. Let me know if further changes are needed.

**Comment by KyleTryon** [comment]
You've done it again! 
![](https://media1.giphy.com/media/3ov9jWyZ6N1vZqHVWE/giphy.gif)
