### ISSUE TITLE
Break circleci/codecov orb into its own repository

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/circleci-orbs#188]
This repository is a monorepo of orbs and we no longer want that. The `circleci/codecov` orb should be broken out into its own repository.

A great way to do this is to use the [Orb Starter Kit](https://github.com/CircleCI-Public/orb-starter-kit) (OSK). The OSK will help you create the scaffolding needed for an orb. Then, the orb source from within this repo can be copied over into your scaffold, eventually creating a brand new orb source repository.

You can then link here to your new repository containing the orb.

**Comment by gagandeepp** [comment]
I will take care of this

**Comment by eddiewebb** [comment]
@felicianotech - don't we need to create a repo in our org for this? How would community drive this?

**Comment by felicianotech** [comment]
@eddiewebb Kyle wants people to start with the Orb Starter Kit. We can then clone the repo take ownership of it after. The bigger issue is, I'm not sure if we're keeping these orbs. I've asked on Slack and am waiting for an answer. I've taken the labels off this issue in the meantime.

@gagandeepp I've taken the labels off of this issue as we need to figure out what we want to do with this internally first. Sorry about that.

**Comment by KyleTryon** [comment]
CodeCov has been partnered and now owns their orb: https://circleci.com/orbs/registry/orb/codecov/codecov
