### ISSUE TITLE
Break circleci/gradle orb into its own repository

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/circleci-orbs#189]
This repository is a monorepo of orbs and we no longer want that. The `circleci/gradle` orb should be broken out into its own repository.

A great way to do this is to use the [Orb Starter Kit](https://github.com/CircleCI-Public/orb-starter-kit) (OSK). The OSK will help you create the scaffolding needed for an orb. Then, the orb source from within this repo can be copied over into your scaffold, eventually creating a brand new orb source repository.

You can then link here to your new repository containing the orb.

**Comment by kamontat** [comment]
I will do this.

**Comment by kamontat** [comment]
I just create gradle orb but I not sure that I understand correctly. https://github.com/kamontat/gradle-orb

**Comment by KyleTryon** [comment]
Thank you everyone who participated. The gradle orb can be found here now: https://github.com/CircleCI-Public/gradle-orb
