### ISSUE TITLE
Break circleci/lein-nvd orb into its own repository

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/circleci-orbs#191]
This repository is a monorepo of orbs and we no longer want that. The `circleci/lein-nvd` orb should be broken out into its own repository.

A great way to do this is to use the [Orb Starter Kit](https://github.com/CircleCI-Public/orb-starter-kit) (OSK). The OSK will help you create the scaffolding needed for an orb. Then, the orb source from within this repo can be copied over into your scaffold, eventually creating a brand new orb source repository.

You can then link here to your new repository containing the orb.

**Comment by sccalabr** [comment]
How do I create a pull request for https://github.com/sccalabr/lein-nvd/tree/master/src

**Comment by sccalabr** [comment]
Let me know if this is what you had in mind.

**Comment by michizhou** [comment]
@felicianotech I have included a link to my version of the new repository with the orb source:
https://github.com/michizhou/lein-nvd-orb. I have also created a PR with the source for the lein-nvd  orb inside this repo modified accordingly. Please let me know if further changes are needed.

**Comment by KyleTryon** [comment]
![](https://media1.giphy.com/media/xT5LMQ8rHYTDGFG07e/giphy.gif)

We will review this as soon as possible thank you!

@michizhou
