### ISSUE TITLE
Break circleci/rollbar orb into its own repository

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/circleci-orbs#193]
This repository is a monorepo of orbs and we no longer want that. The `circleci/rollbar` orb should be broken out into its own repository.

A great way to do this is to use the [Orb Starter Kit](https://github.com/CircleCI-Public/orb-starter-kit) (OSK). The OSK will help you create the scaffolding needed for an orb. Then, the orb source from within this repo can be copied over into your scaffold, eventually creating a brand new orb source repository.

You can then link here to your new repository containing the orb.

**Comment by gagandeepp** [comment]
assign this to me

**Comment by cjwilburn** [comment]
If this hasn't been assigned, I'd love to give this one a shot. Thanks!

**Comment by lex111** [comment]
Hi @felicianotech, I break `circleci/rollbar` orb into its own [repository](https://github.com/lex111/rollbar-orb), please take a look. I'm new to Orb, so I could be wrong, but it was interesting to figure it out! 
What else do I need to do?

**Comment by lex111** [comment]
@felicianotech please at least tell me if I need to open a PR with source code breaked orb? I ask because here someone did just that, although it seems to me that is wrong.

**Comment by KyleTryon** [comment]
Rollbar has been partnered and owns their orb: https://circleci.com/orbs/registry/orb/rollbar/deploy
