### ISSUE TITLE
Break circleci/aws-code-deploy orb into its own repository

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/circleci-orbs#194]
This repository is a monorepo of orbs and we no longer want that. The `circleci/aws-code-deploy` orb should be broken out into its own repository.

A great way to do this is to use the [Orb Starter Kit](https://github.com/CircleCI-Public/orb-starter-kit) (OSK). The OSK will help you create the scaffolding needed for an orb. Then, the orb source from within this repo can be copied over into your scaffold, eventually creating a brand new orb source repository.

You can then link here to your new repository containing the orb.

**Comment by eddiewebb** [comment]
https://github.com/CircleCI-Public/aws-code-deploy-orb is open empty repo for anyone that wants to PR the migration.

This is non-trivial as it involves adding the CircleCI config, but we can help get the build running.

**Comment by kevinchee** [comment]
> https://github.com/CircleCI-Public/aws-code-deploy-orb is open empty repo for anyone that wants to PR the migration.
> 
> This is non-trivial as it involves adding the CircleCI config, but we can help get the build running.

@eddiewebb i've just did a PR for [CircleCI-Public/aws-code-deploy-orb](https://github.com/CircleCI-Public/aws-code-deploy-orb ).

**Comment by shawnjohnson** [comment]
Is this something that should still be done? It seems like a good idea, but I don't know if the [PR](https://github.com/CircleCI-Public/aws-code-deploy-orb/pull/1) is out of date now?

**Comment by KyleTryon** [comment]
Hello,

We have completed our transition of moving each orb within this Mono repository into a separate repository. 🎉 

We have addressed this issue here: https://github.com/CircleCI-Public/aws-code-deploy-orb

Thank you to everyone who has participated
