### ISSUE TITLE
circleci/aws-code-deploy isn't on readme

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/circleci-orbs#195]
The `circleci/aws-code-deploy` orb is container within this repository but isn't listed in the readme. It should be.

**Comment by rafael-vitor** [comment]
I'll take care of this

**Comment by eddiewebb** [comment]
@alinebastros, @lenzfliker, @sameertulshyan - please do not open duplicate PRs.

@kevinchee - #194 and #195 are exclusive options, either we add the badge (short term) or move it to its own repo (strategic)

I created https://github.com/CircleCI-Public/aws-code-deploy-orb to support #194
