### ISSUE TITLE
AWS Code Deploy orb missing descriptions for commands

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/circleci-orbs#196]
Each command should have a description.

**Comment by caseydbrown** [comment]
I would love to give this a shot.

**Comment by sameshl** [comment]
@felicianotech I would love to solve this. Could you elaborate a bit on what exactly needs to be done here?

Thanks!

**Comment by KyleTryon** [comment]
Hello,

We have completed our transition of moving each orb within this Mono repository into a separate repository. 🎉 

We have addressed this issue here during the transition: https://github.com/CircleCI-Public/aws-code-deploy-orb

Thank you!
