### ISSUE TITLE
`--dry-run` spelling

### ISSUE THREAD

**Issue by dimaqq** [CircleCI-Public/circleci-orbs#272]
It's spelt `--dryrun` here:

https://github.com/CircleCI-Public/circleci-orbs/blob/master/src/aws-s3/orb.yml#L58

Yet, it's spelt `--dry-run` in the official aws docs:

https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-help.html

I'm confused which is correct 🤔

**Comment by lokst** [comment]
Thanks for reporting this! I believe this is a typo that needs to be fixed in the orb's example, and it should be `--dry-run`.

**Comment by KyleTryon** [comment]
Hello,

We have completed our transition of moving each orb within this Mono repository into a separate repository. 🎉 

We have addressed this issue here: https://github.com/CircleCI-Public/aws-s3-orb/pull/2
