### ISSUE TITLE
What is an orb?

### ISSUE THREAD

**Issue by apeschel** [CircleCI-Public/circleci-orbs#28]
There doesn't seem to be any documentation on what an orb actually is. Looking at this repo, I still don't really have a clue what it is meant to do. Can someone please add a quick description of what an orb is and what it is meant for?

**Comment by bradylill** [comment]
Hi @apeschel, 

Orbs are packages of CircleCI configuration that can be shared across projects. Orbs allow you to make a single bundle of jobs, commands, and executors that can reference each other and can be imported into a CircleCI build configuration and invoked in their own namespace. Orbs are registered with CircleCI, with revisions expressed using the semver pattern.

You can find additional documentation detailing orbs, including how to use and create them, [in this repo](https://github.com/CircleCI-Public/config-preview-sdk/blob/master/docs/README.md).

**Comment by apeschel** [comment]
@bradylill much appreciated, thank you!
