### ISSUE TITLE
Add parameter to circleci-cli/install that sets the CircleCI token in the user config

### ISSUE THREAD

**Issue by kennyjwilli** [CircleCI-Public/circleci-orbs#43]
Would you guys accept a PR for [`circleci-cli/install`](https://github.com/CircleCI-Public/circleci-orbs/blob/3954f6cde0f96da123f7a4f004bc8d914bcedc84/src/circleci-cli/orb.yml#L3) that can optionally take a parameter named `token`. That parameter would be set in `~/.circleci/cli.yml`. It would basically do what you have written [here](https://github.com/CircleCI-Public/circleci-orbs/blob/3954f6cde0f96da123f7a4f004bc8d914bcedc84/.circleci/config.yml#L38).

**Comment by eric-hu** [comment]
Hi Kenny!

We wouldn't want the `circleci-cli` orb to take a parameter for the token value itself. Parameter values must be defined in user config, which shouldn't store any secrets. If you'd like to submit a PR that will read the value from an environment variable, I'd be happy to review that though.

**Comment by iynere** [comment]
why does the circleci-cli orb need a token parameter? afaik, installing the cli does not require a token

**Comment by felicianotech** [comment]
See https://github.com/CircleCI-Public/circleci-orbs/pull/48
