### ISSUE TITLE
Proposal for a temporary private orbs solution

### ISSUE THREAD

**Issue by jungziege** [CircleCI-Public/circleci-orbs#51]
Hey @ndintenfass et al! 

I've been talking more internally, and I think having world readable orbs is going to be a dealbreaker for us. But while playing around with helm I came up with a proposal I'd like to run by you all to improve inline orbs, which would solve our issues. 

## Proposal:
Allow inline orbs to be defined in an `orbs/` folder inside `.circleci/`. The orbs would be defined exactly the same way as they are now, but referenced as inline orbs. This would allow us to include a shared orbs repo as a submodule, and share orbs effectively across the organization. It would also (hopefully) be an easy change on your end, since you don't have to worry about making per-org orbs repositories. 

## Background
The inspiration for this comes form helm packages. A helm package is created by merging a bunch of templates (stored in a `templates/` subdirectory) together, and supplying the templates with an associated `values.yml` file. From our perspective, it's a very effective solution for config sharing, because we as a central SRE team can publish templates that teams can include just by copying a file. Keeping the convention of "don't edit templates" or "don't edit the `orbs/` folder" is much easier than providing a set of inline orbs for teams to copy and paste into their circle.yml.

**Comment by ndintenfass** [comment]
This was actually exactly our original design. We rant into problems with how it would impact github rate limiting to pull down arbitrarily large number of files at build time. That said, I have set aside the “local” namespace, hoping to use it for something almost exactly like what you’re describing. This is great feedback, so keep it coming.

**Comment by KyleTryon** [comment]
Private orbs are in the works internally via the product team. Closing this issue as this repo will soon be archived. Each orb now lives in a separate repo. Thank you.

Voting for this feature can be done here:

https://ideas.circleci.com/ideas/CCI-I-704

https://ideas.circleci.com/ideas/CCI-I-606
