### ISSUE TITLE
Heroku orb `deploy-via-git` doesn't work when pushing master branches

### ISSUE THREAD

**Issue by realyze** [CircleCI-Public/circleci-orbs#66]
This line
```
git push https://heroku:<< parameters.api-key >>@git.heroku.com/<< parameters.app-name >>.git << parameters.branch >>
```
(https://github.com/CircleCI-Public/circleci-orbs/blob/master/src/heroku/orb.yml#L65) should rather be:
```
git push https://heroku:<< parameters.api-key >>@git.heroku.com/<< parameters.app-name >>.git << parameters.branch >>:master
```
I believe.

**Comment by iynere** [comment]
@realyze thank you !

do you have a link to a circleci job where you saw this error that you could share ? just want to make sure i understand what's going on before i make the change.

**Comment by iynere** [comment]
@realyze this should be fixed now, thank you !
