### ISSUE TITLE
Need easy way to compare orb source at, e.g., v1.x vs. v1.y

### ISSUE THREAD

**Issue by iynere** [CircleCI-Public/circleci-orbs#75]
since [orbs are used in other orbs](https://github.com/CircleCI-Public/circleci-orbs/pull/74), and since sometimes things like parameter names/types, etc., change between releases, it would be very helpful to, for example, in evaluating the previously linked PR, be able to quickly, on GitHub, compare aws-cli-orb 0.0.1 to v0.1.4, to rule out breaking changes

while this is possible from within the circleci CLI, i think a nice way to do it in the monorepo (or in individual orb repositories, & this is something i've already been thinking about for orbs repos' best practices) would be to use git tags/releases in concordance w/ orb prod releases

we can get the new orb release version at the very end of the `master` publishing flow, after we've promoted the latest commit-dev release to prod; and from there, we can retroactively tag/release the same version on GitHub, either in a couple steps after the main prod-promote step, or else in a new CCI job

this will make a `git diff` between version super simple & will make the previously mentioned scenario much more easily navigable

**Comment by iynere** [comment]
thoughts ? @eddiewebb or @ndintenfass

**Comment by KyleTryon** [comment]
Closing. This can be tied to git releases if enabled in the OSK. Otherwise, we can investigate a "diff" CLI command.
