### ISSUE TITLE
Convert all relevant `string` params to `env_var_name`

### ISSUE THREAD

**Issue by iynere** [CircleCI-Public/circleci-orbs#79]
we should encourage this new usage pattern as much as possible to boost adoption by partners, etc.

https://circleci.com/docs/2.0/reusing-config/#environment-variable-name

**Comment by iynere** [comment]
@etorix @KyleTryon no pressure but if ya'll wanna help w/ this, you're more than welcome to !

**Comment by KyleTryon** [comment]
@iynere Any thoughts on situations where we do not want to require an environment variables but leave it as an option where the default could be an environment variable but _can_ be overwritten by a string if needed?

This is currently how the webhook is set for the Slack Orb. Currently, an env var is the default but I want to leave the ability to add a custom webhook url at any point.

example: https://github.com/CircleCI-Public/slack-orb/blob/master/src/%40orb.yml#L16

**Comment by iynere** [comment]
@KyeTryon in that case, i'd say leave it a string 😄
