### ISSUE TITLE
CodeCov Orb Location

### ISSUE THREAD

**Issue by hutson** [CircleCI-Public/circleci-orbs#86]
I noticed that this repository contains an Orb for CodeCov, but I don't believe it's related to the one published here - https://circleci.com/orbs/registry/orb/codecov/codecov

I couldn't actually find this repository's CodeCov Orb on the registry.

Is this repository's Orb maintained, or supported?

**Comment by eddiewebb** [comment]
Codeciov orb source is https://github.com/codecov/codecov-circleci-orb I've opened PR to remove the confusing source.

**Comment by lokst** [comment]
@hutson Closing this issue as the deprecated code has been removed from the repository. In the near future we will officially launch the ability for orb authors to declare a link to their orb's homepage which will be shown in the orb registry. This will help clarify where an orb's repository is!
